# Generated by Django 2.2.7 on 2019-11-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='year',
        ),
    ]
