# Generated by Django 2.2.7 on 2019-11-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_remove_music_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='length',
        ),
        migrations.RemoveField(
            model_name='album',
            name='number_of_musics',
        ),
    ]
