# Generated by Django 2.2.7 on 2019-11-16 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_auto_20191116_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='age',
        ),
    ]
