# Generated by Django 2.2.7 on 2019-11-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_remove_artist_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('username',),
            },
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ('title',)},
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='musics.Person')),
                ('musics', models.ManyToManyField(related_name='playlists', to='musics.Music')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
