# Generated by Django 2.2.7 on 2019-12-08 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0008_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='musics.Artist'),
        ),
    ]
